### ISSUE TITLE
How can I get the me route work

### ISSUE THREAD

**Issue by yaoyonstudio** [marcocastignoli/lumen_auth#1]
Hello.
Thanks you for this example.

I tested and everything went well except the "users/me" route;

The following code is the function of me()

public function me(){
      if (Gate::denies('authorization', [ class_basename($this), __FUNCTION__ ] )) {
          abort(403);
      }
      return Auth::user();
    }

I use the route "http://localhost:8000/users/me" and I got a error:

"HttpException in RegistersExceptionHandlers.php line 32:"

I 'm wondering how can I get  this works. Should I create a method for it .

many thanks...

**Comment by marcocastignoli** [comment]
Is that a 500 error? You first have to add authorizations in the table.

**Comment by yaoyonstudio** [comment]
Thanks for reply. You mean the "authorizations" table in my mysql, I have a "authorizations" table in my mysql , and it's empty. but I don't know how to make it work. 

the "authorizations" table have three main fields [auth,controller,action], how to add the value in it .

thank you very much.

**Comment by marcocastignoli** [comment]
Auth column is a level of authorization corresponding to the auth column in the user table. So if you want to use UserController@me with your account, you need to set an auth for your account in the users table (let's say 0) and then add in the authorizations table: auth=>0, controller=>UserController, action=>me.

The auth column is a group ID of authorizations, so users with auth 0 have all the authorizations you set in the authorizations table with auth 0.

I hope it is clear, ask if you have questions.

**Comment by yaoyonstudio** [comment]
Thanks very much.
Here's my user table:
![user_table](https://cloud.githubusercontent.com/assets/13121726/14484985/ba2ff128-0186-11e6-962f-fb6c036047b5.jpg)

Here's my authorizations table:
![authorizations_table](https://cloud.githubusercontent.com/assets/13121726/14484994/bfcd2452-0186-11e6-9789-bd9e997fb1ba.jpg)

Here's what I request in POSTMAN:
![result](https://cloud.githubusercontent.com/assets/13121726/14484967/9a5c5fbc-0186-11e6-9985-b5e753faa6ed.jpg)

I'm also get the error: HttpException in RegistersExceptionHandlers.php line 32:

should I pass some header information or parameters...
and how exactly to do that ??

plus:
because I'm testing in my local machine,so I don't have email server, so I comment the mail function code, and modify the comfirmed field manually . and nothing change in the other part of the UserController , is that matter ???

here is my register function.

`public function register(Request $request){
      if ($request->has('username') && $request->has('password') && $request->has('email')) {
        $user = new User;
        $user->username=$request->input('username');
        $user->password=sha1($this->salt.$request->input('password'));
        $user->email=$request->input('email');
        $user->confirmed=false;
        $user->api_token=str_random(60);
        if($user->save()){
          // $url="http://".$_SERVER['SERVER_NAME']."/users/confirm/".$user->api_token;
          // mail('yaoyonstudio@gmail.com', 'ken', "active link: <a href='".$url."'></a>");
          return "SUCCESS";
        } else {
          return "ERROR";
        }
      } else {
        return "INCOMPLETE";
      }
    }`


I'm so embarrasing...  get you so much trouble.

thank you so much.

**Comment by marcocastignoli** [comment]
First send your username and pass

![immagine](https://cloud.githubusercontent.com/assets/10226180/14486231/1523bf2c-015c-11e6-81fd-cca6b6f4ab1b.png)

it will return a token, copy the token and past it here

![immagine1](https://cloud.githubusercontent.com/assets/10226180/14486321/6a95be74-015c-11e6-905f-617a5b32b927.png)

**Comment by yaoyonstudio** [comment]
![11](https://cloud.githubusercontent.com/assets/13121726/14486572/421af192-0190-11e6-847c-3f024dadf30f.jpg)

![222](https://cloud.githubusercontent.com/assets/13121726/14486574/4277c1e2-0190-11e6-8721-f26dc56e07a7.jpg)

I 'm get the same error . 
I 'll build a new project and get another try.
Thank you very much.

**Comment by yaoyonstudio** [comment]
Hi, marcocastignoli !

I found out the reason. I made a fool mistake.

your code works fine . And it's very practical.

sorry about bother you , Thank you very much.

**Comment by marcocastignoli** [comment]
No problem :)
